openapi: 3.0.0
info:
  title: Authentication api
  description: An API for authentication purposes
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0-oas3
paths:
  /login:
    post:
      description: have access to ressources
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        '201':
          description: created
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /users:
    post:
      description: create a user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '201':
          description: created
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    get:
      description: get the list of users
      operationId: getUsers
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
      security:
        -  bearerAuth: [ ]

  /users/{e_mail}:
    put:
      description: updates a single user based on the e_mail supplied
      operationId: updateUser
      parameters:
        - name: e_mail
          in: path
          required: true
          schema:
            type: string
            description: The user e_mail
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    delete:
      description: deletes a single user based on the e_mail supplied
      operationId: deleteUser
      parameters:
        - name: e_mail
          in: path
          required: true
          schema:
            type: string
            description: The user e_mail
      responses:
        '200':
          description: success
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /users/{e_mail}/block:
    patch:
      description: the admin block a user
      operationId: blockUser
      parameters:
        - name: e_mail
          in: path
          required: true
          schema:
            type: string
            description: The user e_mail
      responses:
        '200':
          description: success
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /users/{e_mail}/unblock:
    patch:
      description: the admin block a user
      operationId: unblockUser
      parameters:
        - name: e_mail
          in: path
          required: true
          schema:
            type: string
            description: The user e_mail
      responses:
        '200':
          description: success
        '401':
          $ref: '#/components/responses/UnauthorizedError'

components:
  securitySchemes:
    bearerAuth:
      description: "Give the token at each user"
      type: "apiKey"
      name: "Authorization"
      in: "header"
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        password:
          type: string
        role:
          type: string
        isBlock:
          type: boolean
    Credentials:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
  responses:
    UnauthorizedError:
      description: Access token is missing or is invalid
