openapi: '3.0.0'
info:
  title: Authentication api
  description: An API for authentication
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0-oas3
servers:
  - url: https://localhost:8080/gestionCours
paths:
  /subjects:
    post:
      operationId: createSubject
      description: create a new subject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subject'
      responses:
        '200':
          description: Subject creation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subject'
        '201':
          description: created
        '401':
          description: unexpected error
        '403':
          description: forbidden
        '404':
          description: not found
    get:
      description: get the list of all subjects
      operationId: getSubjects
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subject'
        '401':
          description: unexpected error
  /subjects/{id}:
    get:
      description: gets a single subject based on the ID supplied
      operationId: getASubject
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
            description: The user ID
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subject'
        '401':
          description: unexpected error
        '403':
          description: forbidden
        '404':
          description: not found
    put:
      operationId: UpdateSubject
      description: update a subject
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subject'
      responses:
        '200':
          description: subject response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subject'
        '201':
          description: updated
        '401':
          description: unexpected error
        '403':
          description: forbidden
        '404':
          description: not found

    delete:
      description: delete an existing subject base on the ID supplied
      operationId: deleteSubject
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Subject deleted
        default:
          description: unexpected error


  /enrollments:
    post:
      operationId: createEnrollment
      description: create an Enrollment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Enrollment'
      responses:
        '200':
          description: enrollment response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Enrollment'
        '201':
          description: created
        '401':
          description: unexpected error
        '403':
          description: forbidden
        '404':
          description: not found
    get:
      description: get the list of all enrollments
      operationId: getEnrollments
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Enrollment'
        '401':
          description: unexpected error

  /enrollments/{id}:
    get:
      description: Returns an enrollment based on a single ID
      operationId: get enrollment by id
      parameters:
        - name: id
          in: path
          description: ID of enrollment to fetch
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: enrollment response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Enrollment'
        default:
          description: unexpected error
    delete:
      description: delete a single enrollment on the ID supplied
      operationId: deleteEnrollment
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: enrollment deleted
        default:
          description: unexpected error
    put:
      operationId: UpdateEnrollment
      description: update an Enrollment
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Enrollment'
      responses:
        '200':
          description: enrollment response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Enrollment'
        '201':
          description: updated
        '401':
          description: unexpected error
        '403':
          description: forbidden
        '404':
          description: not found


  /labos:
    post:
      operationId: createLabo
      description: create a Labo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Labo'
      responses:
        '200':
          description: labo creation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Labo'
        '201':
          description: created
        '401':
          description: unexpected error
        '403':
          description: forbidden
        '404':
          description: not found
    get:
      description: get the list of all Labos
      operationId: getLabos
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Labo'
        '401':
          description: unexpected error
  /labos/{id}:
    get:
      description: Returns an labo based on a single ID
      operationId: get labo by id
      parameters:
        - name: id
          in: path
          description: ID of labo to fetch
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: labo response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Labo'
        default:
          description: unexpected error

    delete:
      description: delete a single labo on the id supplied
      operationId: deleteLabo
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: labo deleted
        default:
          description: unexpected error
    put:
      operationId: UpdateLabo
      description: update an Labo
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Labo'
      responses:
        '200':
          description: Labo response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Labo'
        '201':
          description: updated
        '401':
          description: unexpected error
        '403':
          description: forbidden
        '404':
          description: not found


components:
  schemas:
    Subject:
      type: object
      required:
        - name
        - credits_etcs
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        credits_etcs:
          type: integer
          format: int64
        laboId:
          type: integer
          format: int64
    SubjectList:
      allOf:
        - $ref: '#/components/schemas/Subject'
        - type: object
          properties:
            id:
              type : integer
              format: int64
    Enrollment:
      type: object
      required:
        - subject_id
        - user_email
      properties:
        id:
          type: integer
          format: int64
        subject_id:
          type: integer
          format: int64
        user_email:
          type: string
    EnrollmentList:
      allOf:
        - $ref: '#/components/schemas/Enrollment'
        - type: object
          properties:
            id:
              type: integer
              format: int64
    Labo:
      type: object
      required:
        - labo_name
        - ponderation
      properties:
        id:
          type: integer
          format: int64
        labo_name:
          type: string
        ponderation:
          type: integer
          format: int32
    LaboList:
      allOf:
        - $ref: '#/components/schemas/Labo'
        - type: object
          properties:
            name:
              type: string
            ponderation:
              type: integer
              format: int64