use gestionCours;

INSERT INTO gestionCours.subject_entity (name, credits_etcs)
	 VALUES
		 ('Teleinformatique de base (TIB)', 4),
		 ('Introduction a la securite de l information (ISI)', 4),
		 ('Analyse mathematique (ANA)', 6),
		 ('Mathematiques discretes (MAD)', 6),
		 ('Mathematiques de base pour TIC (MBT)', 5),
		 ('Architecture des ordinateurs 2 (ARO2)', 4),
		 ('Architecture des ordinateurs 1 (ARO1)', 5),
		 ('Anglais (Ang)', 4),
		 ('Allemand (ALL)', 4),
		 ('Informatique 1 (INF1)', 10),
		 ('Informatique 2 (INF2)', 10),
		 ('Algorithmes et structures de donnees 1 (ASD1)', 6),
		 ('Protocoles de reseaux (PRS)', 5),
		 ('Administration systeme (ADS)', 3),
		 ('LAN filaires et sans fils (LAN)', 3),
		 ('Couche physique et liaison (CPL)', 2),
		 ('Probabilites et statistiques (PST)', 5),
		 ('Physique pour TIC (PHY)', 5),
		 ('Planification de reseaux (PLR)', 2),
		 ('Routage avance (RTA)', 3),
		 ('Securite des technologies internet (STI)', 3),
		 ('Securite des systemes d exploitation (SOS)', 4),
		 ('Securite des reseaux (SRX)', 4),
		 ('Serialisation (SER)', 2),
		 ('Reseaux (RES)', 4),
		 ('Signaux analogiques et numeriques (SIG)', 3),
		 ('Programmation orientee objet 1 (POO1)', 6),
		 ('Bases de donnees relationnelles (BDR)', 6),
		 ('Algorithmes et structures de donnees 2 (ASD2)', 4),
		 ('Gestion d entreprise pour TIC (GET)', 3),
		 ('Transmission et modulation (TRM)', 5),
		 ('Storage Area Networking (SAN)', 3),
		 ('Teletrafic (TTR)', 2),
		 ('Systemes d exploitation (SYE)', 4),
		 ('Programmation concurrente (PCO)', 4),
		 ('Cloud Computing (CLD)', 4),
		 ('Securite des reseaux sans fil (SWI)', 4),
		 ('Projet de semestre (PRO)', 2),
		 ('Administration IT (AIT)', 4),
		 ('Applications multi-tiers (AMT)', 6),
		 ('Gestion de reseaux (GRX)', 2);
