use gestionCours;

INSERT INTO gestionCours.Subjects (name, credit_etcs)
	 VALUES
		 ('Teleinformatique de base (TIB)', 4),
		 ('Introduction a la securite de l information (ISI)', 4),
		 ('Analyse mathematique (ANA)', 6),
		 ('Mathematiques discretes (MAD)', 6),
		 ('Mathematiques de base pour TIC (MBT)', 5),
		 ('Architecture des ordinateurs 2 (ARO2)', 4),
		 ('Architecture des ordinateurs 1 (ARO1)', 5),
		 ('Anglais (Ang)', 4),
		 ('Allemand (ALL)', 4),
		 ('Informatique 1 (INF1)', 10),
		 ('Informatique 2 (INF2)', 10),
		 ('Algorithmes et structures de donnees 1 (ASD1)', 6),
		 ('Protocoles de reseaux (PRS)', 5),
		 ('Administration systeme (ADS)', 3),
		 ('LAN filaires et sans fils (LAN)', 3),
		 ('Couche physique et liaison (CPL)', 2),
		 ('Probabilites et statistiques (PST)', 5),
		 ('Physique pour TIC (PHY)', 5),
		 ('Planification de reseaux (PLR)', 2),
		 ('Routage avance (RTA)', 3),
		 ('Securite des technologies internet (STI)', 3),
		 ('Securite des systemes d exploitation (SOS)', 4),
		 ('Securite des reseaux (SRX)', 4),
		 ('Serialisation (SER)', 2),
		 ('Reseaux (RES)', 4),
		 ('Signaux analogiques et numeriques (SIG)', 3),
		 ('Programmation orientee objet 1 (POO1)', 6),
		 ('Bases de donnees relationnelles (BDR)', 6),
		 ('Algorithmes et structures de donnees 2 (ASD2)', 4),
		 ('Gestion d entreprise pour TIC (GET)', 3),
		 ('Transmission et modulation (TRM)', 5),
		 ('Storage Area Networking (SAN)', 3),
		 ('Teletrafic (TTR)', 2),
		 ('Systemes d exploitation (SYE)', 4),
		 ('Programmation concurrente (PCO)', 4),
		 ('Cloud Computing (CLD)', 4),
		 ('Securite des reseaux sans fil (SWI)', 4),
		 ('Projet de semestre (PRO)', 2),
		 ('Administration IT (AIT)', 4),
		 ('Applications multi-tiers (AMT)', 6),
		 ('Gestion de reseaux (GRX)', 2);

INSERT INTO gestionCours.Enrollments (email, name)
	 VALUES
		 ('paulo@heig-vd.ch','Teleinformatique de base (TIB)'),
		 ('cbreewood@heig-vd.ch','Teleinformatique de base (TIB)'),
		 ('afenech2@heig-vd.ch','Teleinformatique de base (TIB)'),
		 ('wgallyon8@heig-vd.ch', 'Teleinformatique de base (TIB)'),
		 ('lverillo9@heig-vd.ch', 'Teleinformatique de base (TIB)'),
		 ('slimpenny3@heig-vd.ch', 'Teleinformatique de base (TIB)'),
		 ('rpynner4@heig-vd.ch','Teleinformatique de base (TIB)'),
		 ('bpierce6@heig-vd.ch','Teleinformatique de base (TIB)'),
		 ('cerrichelli7@heig-vd.ch', 'Teleinformatique de base (TIB)'),
		 ('lesly.kamdem@heig-vd.ch','Teleinformatique de base (TIB)'),
		 ('natacha.kegne@heig-vd.ch','Teleinformatique de base (TIB)'),
		 ('paulo@heig-vd.ch','Introduction a la securite de l information (ISI)'),
		 ('cbreewood@heig-vd.ch','Introduction a la securite de l information (ISI)'),
		 ('wgallyon8@heig-vd.ch','Introduction a la securite de l information (ISI)'),
		 ('lverillo9@heig-vd.ch', 'Introduction a la securite de l information (ISI)'),
		 ('slimpenny3@heig-vd.ch', 'Introduction a la securite de l information (ISI)'),
		 ('rpynner4@heig-vd.ch','Introduction a la securite de l information (ISI)'),
		 ('bpierce6@heig-vd.ch','Introduction a la securite de l information (ISI)'),
		 ('cerrichelli7@heig-vd.ch', 'Introduction a la securite de l information (ISI)'),
		 ('lesly.kamdem@heig-vd.ch','Introduction a la securite de l information (ISI)'),
		 ('natacha.kegne@heig-vd.ch','Introduction a la securite de l information (ISI)'),
		 ('nelson.nana@heig-vd.ch','Introduction a la securite de l information (ISI)'),
		 ('yvan.sayom@heig-vd.ch','Introduction a la securite de l information (ISI)'),
		 ('gilles.kegne@heig-vd.ch','Introduction a la securite de l information (ISI)'),
		 ('michel.archange@heig-vd.ch', 'Introduction a la securite de l information (ISI)'),
		 ('paulo@heig-vd.ch','Analyse mathematique (ANA)'),
		 ('cbreewood@heig-vd.ch','Analyse mathematique (ANA)'),
		 ('afenech2@heig-vd.ch','Analyse mathematique (ANA)'),
		 ('wgallyon8@heig-vd.ch', 'Analyse mathematique (ANA)'),
		 ('lverillo9@heig-vd.ch', 'Analyse mathematique (ANA)'),
		 ('slimpenny3@heig-vd.ch', 'Analyse mathematique (ANA)'),
		 ('rpynner4@heig-vd.ch','Analyse mathematique (ANA)'),
		 ('bpierce6@heig-vd.ch','Analyse mathematique (ANA)'),
		 ('cerrichelli7@heig-vd.ch', 'Analyse mathematique (ANA)'),
		 ('lesly.kamdem@heig-vd.ch','Analyse mathematique (ANA)'),
		 ('natacha.kegne@heig-vd.ch','Analyse mathematique (ANA)'),
		 ('nelson.nana@heig-vd.ch','Analyse mathematique (ANA)'),
		 ('yvan.sayom@heig-vd.ch','Analyse mathematique (ANA)'),
		 ('gilles.kegne@heig-vd.ch','Analyse mathematique (ANA)'),
		 ('michel.archange@heig-vd.ch', 'Analyse mathematique (ANA)'),
		 ('paulo@heig-vd.ch','Mathematiques discretes (MAD)'),
		 ('cbreewood@heig-vd.ch','Mathematiques discretes (MAD)'),
		 ('afenech2@heig-vd.ch','Mathematiques discretes (MAD)'),
		 ('wgallyon8@heig-vd.ch', 'Mathematiques discretes (MAD)'),
		 ('lverillo9@heig-vd.ch', 'Mathematiques discretes (MAD)'),
		 ('slimpenny3@heig-vd.ch', 'Mathematiques discretes (MAD)'),
		 ('rpynner4@heig-vd.ch','Mathematiques discretes (MAD)'),
		 ('bpierce6@heig-vd.ch','Mathematiques discretes (MAD)'),
		 ('cerrichelli7@heig-vd.ch', 'Mathematiques discretes (MAD)'),
		 ('lesly.kamdem@heig-vd.ch','Mathematiques discretes (MAD)'),
		 ('natacha.kegne@heig-vd.ch','Mathematiques discretes (MAD)'),
		 ('nelson.nana@heig-vd.ch','Mathematiques discretes (MAD)'),
		 ('yvan.sayom@heig-vd.ch','Mathematiques discretes (MAD)'),
		 ('gilles.kegne@heig-vd.ch','Mathematiques discretes (MAD)'),
		 ('michel.archange@heig-vd.ch', 'Mathematiques discretes (MAD)'),
		 ('paulo@heig-vd.ch','Mathematiques de base pour TIC (MBT)'),
		 ('cbreewood@heig-vd.ch','Mathematiques de base pour TIC (MBT)'),
		 ('afenech2@heig-vd.ch','Mathematiques de base pour TIC (MBT)'),
		 ('wgallyon8@heig-vd.ch', 'Mathematiques de base pour TIC (MBT)'),
		 ('lverillo9@heig-vd.ch', 'Mathematiques de base pour TIC (MBT)'),
		 ('slimpenny3@heig-vd.ch', 'Mathematiques de base pour TIC (MBT)'),
		 ('rpynner4@heig-vd.ch','Mathematiques de base pour TIC (MBT)'),
		 ('bpierce6@heig-vd.ch','Mathematiques de base pour TIC (MBT)'),
		 ('cerrichelli7@heig-vd.ch', 'Mathematiques de base pour TIC (MBT)'),
		 ('lesly.kamdem@heig-vd.ch','Mathematiques de base pour TIC (MBT)'),
		 ('natacha.kegne@heig-vd.ch','Mathematiques de base pour TIC (MBT)'),
		 ('paulo@heig-vd.ch','Architecture des ordinateurs 2 (ARO2)'),
		 ('cbreewood@heig-vd.ch','Architecture des ordinateurs 2 (ARO2)'),
		 ('afenech2@heig-vd.ch','Architecture des ordinateurs 2 (ARO2)'),
		 ('wgallyon8@heig-vd.ch', 'Architecture des ordinateurs 2 (ARO2)'),
		 ('lverillo9@heig-vd.ch', 'Architecture des ordinateurs 2 (ARO2)'),
		 ('slimpenny3@heig-vd.ch', 'Architecture des ordinateurs 2 (ARO2)'),
		 ('rpynner4@heig-vd.ch','Architecture des ordinateurs 2 (ARO2)'),
		 ('bpierce6@heig-vd.ch','Architecture des ordinateurs 2 (ARO2)'),
		 ('cerrichelli7@heig-vd.ch', 'Architecture des ordinateurs 2 (ARO2)'),
		 ('lesly.kamdem@heig-vd.ch','Architecture des ordinateurs 2 (ARO2)'),
		 ('natacha.kegne@heig-vd.ch','Architecture des ordinateurs 2 (ARO2)'),
		 ('nelson.nana@heig-vd.ch','Architecture des ordinateurs 2 (ARO2)'),
		 ('yvan.sayom@heig-vd.ch','Architecture des ordinateurs 2 (ARO2)'),
		 ('gilles.kegne@heig-vd.ch','Architecture des ordinateurs 2 (ARO2)'),
		 ('michel.archange@heig-vd.ch', 'Architecture des ordinateurs 2 (ARO2)'),
		 ('paulo@heig-vd.ch','Architecture des ordinateurs 1 (ARO1)'),
		 ('cbreewood@heig-vd.ch','Architecture des ordinateurs 1 (ARO1)'),
		 ('afenech2@heig-vd.ch','Architecture des ordinateurs 1 (ARO1)'),
		 ('wgallyon8@heig-vd.ch', 'Architecture des ordinateurs 1 (ARO1)'),
		 ('lverillo9@heig-vd.ch', 'Architecture des ordinateurs 1 (ARO1)'),
		 ('slimpenny3@heig-vd.ch', 'Architecture des ordinateurs 1 (ARO1)'),
		 ('rpynner4@heig-vd.ch','Architecture des ordinateurs 1 (ARO1)'),
		 ('bpierce6@heig-vd.ch','Architecture des ordinateurs 1 (ARO1)'),
		 ('cerrichelli7@heig-vd.ch', 'Architecture des ordinateurs 1 (ARO1)'),
		 ('lesly.kamdem@heig-vd.ch','Architecture des ordinateurs 1 (ARO1)'),
		 ('natacha.kegne@heig-vd.ch','Architecture des ordinateurs 1 (ARO1)'),
		 ('nelson.nana@heig-vd.ch','Architecture des ordinateurs 1 (ARO1)'),
		 ('yvan.sayom@heig-vd.ch','Architecture des ordinateurs 1 (ARO1)'),
		 ('gilles.kegne@heig-vd.ch','Architecture des ordinateurs 1 (ARO1)'),
		 ('michel.archange@heig-vd.ch', 'Architecture des ordinateurs 1 (ARO1)'),
		 ('paulo@heig-vd.ch','Anglais (Ang)'),
		 ('cbreewood@heig-vd.ch','Anglais (Ang)'),
		 ('afenech2@heig-vd.ch','Anglais (Ang)'),
		 ('wgallyon8@heig-vd.ch', 'Anglais (Ang)'),
		 ('lverillo9@heig-vd.ch', 'Anglais (Ang)'),
		 ('slimpenny3@heig-vd.ch', 'Anglais (Ang)'),
		 ('rpynner4@heig-vd.ch','Anglais (Ang)'),
		 ('bpierce6@heig-vd.ch','Anglais (Ang)'),
		 ('cerrichelli7@heig-vd.ch', 'Anglais (Ang)'),
		 ('lesly.kamdem@heig-vd.ch','Anglais (Ang)'),
		 ('natacha.kegne@heig-vd.ch','Anglais (Ang)'),
		 ('nelson.nana@heig-vd.ch','Anglais (Ang)'),
		 ('yvan.sayom@heig-vd.ch','Anglais (Ang)'),
		 ('gilles.kegne@heig-vd.ch','Anglais (Ang)'),
		 ('michel.archange@heig-vd.ch', 'Anglais (Ang)'),
		 ('paulo@heig-vd.ch','Allemand (ALL)'),
		 ('cbreewood@heig-vd.ch','Allemand (ALL)'),
		 ('afenech2@heig-vd.ch','Allemand (ALL)'),
		 ('wgallyon8@heig-vd.ch', 'Allemand (ALL)'),
		 ('lverillo9@heig-vd.ch', 'Allemand (ALL)'),
		 ('slimpenny3@heig-vd.ch', 'Allemand (ALL)'),
		 ('rpynner4@heig-vd.ch','Allemand (ALL)'),
		 ('bpierce6@heig-vd.ch','Allemand (ALL)'),
		 ('cerrichelli7@heig-vd.ch', 'Allemand (ALL)'),
		 ('lesly.kamdem@heig-vd.ch','Allemand (ALL)'),
		 ('natacha.kegne@heig-vd.ch','Allemand (ALL)'),
		 ('nelson.nana@heig-vd.ch','Allemand (ALL)'),
		 ('yvan.sayom@heig-vd.ch','Allemand (ALL)'),
		 ('gilles.kegne@heig-vd.ch','Allemand (ALL)'),
		 ('michel.archange@heig-vd.ch', 'Allemand (ALL)'),
		 ('paulo@heig-vd.ch','Informatique 1 (INF1)'),
		 ('cbreewood@heig-vd.ch','Informatique 1 (INF1)'),
		 ('afenech2@heig-vd.ch','Informatique 1 (INF1)'),
		 ('wgallyon8@heig-vd.ch', 'Informatique 1 (INF1)'),
		 ('lverillo9@heig-vd.ch', 'Informatique 1 (INF1)'),
		 ('slimpenny3@heig-vd.ch', 'Informatique 1 (INF1)'),
		 ('rpynner4@heig-vd.ch','Informatique 1 (INF1)'),
		 ('bpierce6@heig-vd.ch','Informatique 1 (INF1)'),
		 ('cerrichelli7@heig-vd.ch', 'Informatique 1 (INF1)'),
		 ('lesly.kamdem@heig-vd.ch','Informatique 1 (INF1)'),
		 ('natacha.kegne@heig-vd.ch','Informatique 1 (INF1)'),
		 ('nelson.nana@heig-vd.ch','Informatique 1 (INF1)'),
		 ('yvan.sayom@heig-vd.ch','Informatique 1 (INF1)'),
		 ('gilles.kegne@heig-vd.ch','Informatique 1 (INF1)'),
		 ('michel.archange@heig-vd.ch', 'Informatique 1 (INF1)'),
		 ('paulo@heig-vd.ch','Informatique 2 (INF2)'),
		 ('cbreewood@heig-vd.ch','Informatique 2 (INF2)'),
		 ('afenech2@heig-vd.ch','Informatique 2 (INF2)'),
		 ('wgallyon8@heig-vd.ch', 'Informatique 2 (INF2)'),
		 ('lverillo9@heig-vd.ch', 'Informatique 2 (INF2)'),
		 ('slimpenny3@heig-vd.ch', 'Informatique 2 (INF2)'),
		 ('rpynner4@heig-vd.ch','Informatique 2 (INF2)'),
		 ('bpierce6@heig-vd.ch','Informatique 2 (INF2)'),
		 ('cerrichelli7@heig-vd.ch', 'Informatique 2 (INF2)'),
		 ('lesly.kamdem@heig-vd.ch','Informatique 2 (INF2)'),
		 ('natacha.kegne@heig-vd.ch','Informatique 2 (INF2)'),
		 ('nelson.nana@heig-vd.ch','Informatique 2 (INF2)'),
		 ('yvan.sayom@heig-vd.ch','Informatique 2 (INF2)'),
		 ('gilles.kegne@heig-vd.ch','Informatique 2 (INF2)'),
		 ('michel.archange@heig-vd.ch', 'Informatique 2 (INF2)'),
		 ('paulo@heig-vd.ch','Algorithmes et structures de donnees 1 (ASD1)'),
		 ('cbreewood@heig-vd.ch','Algorithmes et structures de donnees 1 (ASD1)'),
		 ('afenech2@heig-vd.ch','Algorithmes et structures de donnees 1 (ASD1)'),
		 ('wgallyon8@heig-vd.ch', 'Algorithmes et structures de donnees 1 (ASD1)'),
		 ('lverillo9@heig-vd.ch', 'Algorithmes et structures de donnees 1 (ASD1)'),
		 ('slimpenny3@heig-vd.ch', 'Algorithmes et structures de donnees 1 (ASD1)'),
		 ('rpynner4@heig-vd.ch','Algorithmes et structures de donnees 1 (ASD1)'),
		 ('bpierce6@heig-vd.ch','Algorithmes et structures de donnees 1 (ASD1)'),
		 ('cerrichelli7@heig-vd.ch', 'Algorithmes et structures de donnees 1 (ASD1)'),
		 ('lesly.kamdem@heig-vd.ch','Algorithmes et structures de donnees 1 (ASD1)'),
		 ('natacha.kegne@heig-vd.ch','Algorithmes et structures de donnees 1 (ASD1)'),
		 ('nelson.nana@heig-vd.ch','Algorithmes et structures de donnees 1 (ASD1)'),
		 ('yvan.sayom@heig-vd.ch','Algorithmes et structures de donnees 1 (ASD1)'),
		 ('gilles.kegne@heig-vd.ch','Algorithmes et structures de donnees 1 (ASD1)'),
		 ('michel.archange@heig-vd.ch', 'Algorithmes et structures de donnees 1 (ASD1)'),
		 ('paulo@heig-vd.ch','Protocoles de reseaux (PRS)'),
		 ('cbreewood@heig-vd.ch','Protocoles de reseaux (PRS)'),
		 ('afenech2@heig-vd.ch','Protocoles de reseaux (PRS)'),
		 ('wgallyon8@heig-vd.ch', 'Protocoles de reseaux (PRS)'),
		 ('lverillo9@heig-vd.ch', 'Protocoles de reseaux (PRS)'),
		 ('slimpenny3@heig-vd.ch', 'Protocoles de reseaux (PRS)'),
		 ('rpynner4@heig-vd.ch','Protocoles de reseaux (PRS)'),
		 ('bpierce6@heig-vd.ch','Protocoles de reseaux (PRS)'),
		 ('cerrichelli7@heig-vd.ch', 'Protocoles de reseaux (PRS)'),
		 ('lesly.kamdem@heig-vd.ch','Protocoles de reseaux (PRS)'),
		 ('natacha.kegne@heig-vd.ch','Protocoles de reseaux (PRS)'),
		 ('nelson.nana@heig-vd.ch','Protocoles de reseaux (PRS)'),
		 ('yvan.sayom@heig-vd.ch','Protocoles de reseaux (PRS)'),
		 ('gilles.kegne@heig-vd.ch','Protocoles de reseaux (PRS)'),
		 ('michel.archange@heig-vd.ch', 'Protocoles de reseaux (PRS)'),
		 ('paulo@heig-vd.ch','Administration systeme (ADS)'),
		 ('cbreewood@heig-vd.ch','Administration systeme (ADS)'),
		 ('afenech2@heig-vd.ch','Administration systeme (ADS)'),
		 ('wgallyon8@heig-vd.ch', 'Administration systeme (ADS)'),
		 ('lverillo9@heig-vd.ch', 'Administration systeme (ADS)'),
		 ('slimpenny3@heig-vd.ch', 'Administration systeme (ADS)'),
		 ('rpynner4@heig-vd.ch','Administration systeme (ADS)'),
		 ('bpierce6@heig-vd.ch','Administration systeme (ADS)'),
		 ('cerrichelli7@heig-vd.ch', 'Administration systeme (ADS)'),
		 ('lesly.kamdem@heig-vd.ch','Administration systeme (ADS)'),
		 ('natacha.kegne@heig-vd.ch','Administration systeme (ADS)'),
		 ('nelson.nana@heig-vd.ch','Administration systeme (ADS)'),
		 ('yvan.sayom@heig-vd.ch','Administration systeme (ADS)'),
		 ('gilles.kegne@heig-vd.ch','Administration systeme (ADS)'),
		 ('michel.archange@heig-vd.ch', 'Administration systeme (ADS)'),
		 ('paulo@heig-vd.ch','LAN filaires et sans fils (LAN)'),
		 ('cbreewood@heig-vd.ch','LAN filaires et sans fils (LAN)'),
		 ('afenech2@heig-vd.ch','LAN filaires et sans fils (LAN)'),
		 ('wgallyon8@heig-vd.ch', 'LAN filaires et sans fils (LAN)'),
		 ('lverillo9@heig-vd.ch', 'LAN filaires et sans fils (LAN)'),
		 ('slimpenny3@heig-vd.ch', 'LAN filaires et sans fils (LAN)'),
		 ('rpynner4@heig-vd.ch','LAN filaires et sans fils (LAN)'),
		 ('bpierce6@heig-vd.ch','LAN filaires et sans fils (LAN)'),
		 ('cerrichelli7@heig-vd.ch', 'LAN filaires et sans fils (LAN)'),
		 ('lesly.kamdem@heig-vd.ch','LAN filaires et sans fils (LAN)'),
		 ('natacha.kegne@heig-vd.ch','LAN filaires et sans fils (LAN)'),
		 ('paulo@heig-vd.ch','Couche physique et liaison (CPL)'),
		 ('cbreewood@heig-vd.ch','Couche physique et liaison (CPL)'),
		 ('afenech2@heig-vd.ch','Couche physique et liaison (CPL)'),
		 ('wgallyon8@heig-vd.ch', 'Couche physique et liaison (CPL)'),
		 ('lverillo9@heig-vd.ch', 'Couche physique et liaison (CPL)'),
		 ('slimpenny3@heig-vd.ch', 'Couche physique et liaison (CPL)'),
		 ('rpynner4@heig-vd.ch','Couche physique et liaison (CPL)'),
		 ('bpierce6@heig-vd.ch','Couche physique et liaison (CPL)'),
		 ('cerrichelli7@heig-vd.ch', 'Couche physique et liaison (CPL)'),
		 ('lesly.kamdem@heig-vd.ch','Couche physique et liaison (CPL)'),
		 ('natacha.kegne@heig-vd.ch','Couche physique et liaison (CPL)'),
		 ('paulo@heig-vd.ch','Probabilites et statistiques (PST)'),
		 ('cbreewood@heig-vd.ch','Probabilites et statistiques (PST)'),
		 ('afenech2@heig-vd.ch','Probabilites et statistiques (PST)'),
		 ('wgallyon8@heig-vd.ch', 'Probabilites et statistiques (PST)'),
		 ('lverillo9@heig-vd.ch', 'Probabilites et statistiques (PST)'),
		 ('slimpenny3@heig-vd.ch', 'Probabilites et statistiques (PST)'),
		 ('rpynner4@heig-vd.ch','Probabilites et statistiques (PST)'),
		 ('nelson.nana@heig-vd.ch','Probabilites et statistiques (PST)'),
		 ('yvan.sayom@heig-vd.ch','Probabilites et statistiques (PST)'),
		 ('gilles.kegne@heig-vd.ch','Probabilites et statistiques (PST)'),
		 ('michel.archange@heig-vd.ch', 'Probabilites et statistiques (PST)'),
		 ('cbreewood@heig-vd.ch','Physique pour TIC (PHY)'),
		 ('afenech2@heig-vd.ch','Physique pour TIC (PHY)'),
		 ('bpierce6@heig-vd.ch','Physique pour TIC (PHY)'),
		 ('cerrichelli7@heig-vd.ch', 'Physique pour TIC (PHY)'),
		 ('lesly.kamdem@heig-vd.ch','Physique pour TIC (PHY)'),
		 ('natacha.kegne@heig-vd.ch','Physique pour TIC (PHY)'),
		 ('cbreewood@heig-vd.ch','Planification de reseaux (PLR)'),
		 ('afenech2@heig-vd.ch','Planification de reseaux (PLR)'),
		 ('nelson.nana@heig-vd.ch','Planification de reseaux (PLR)'),
		 ('yvan.sayom@heig-vd.ch','Planification de reseaux (PLR)'),
		 ('gilles.kegne@heig-vd.ch','Planification de reseaux (PLR)'),
		 ('michel.archange@heig-vd.ch', 'Planification de reseaux (PLR)'),
		 ('cbreewood@heig-vd.ch','Routage avance (RTA)'),
		 ('afenech2@heig-vd.ch','Routage avance (RTA)'),
		 ('nelson.nana@heig-vd.ch','Routage avance (RTA)'),
		 ('yvan.sayom@heig-vd.ch','Routage avance (RTA)'),
		 ('gilles.kegne@heig-vd.ch','Routage avance (RTA)'),
		 ('michel.archange@heig-vd.ch', 'Routage avance (RTA)'),
		 ('wgallyon8@heig-vd.ch', 'Securite des technologies internet (STI)'),
		 ('lverillo9@heig-vd.ch', 'Securite des technologies internet (STI)'),
		 ('slimpenny3@heig-vd.ch', 'Securite des technologies internet (STI)'),
		 ('rpynner4@heig-vd.ch','Securite des technologies internet (STI)'),
		 ('nelson.nana@heig-vd.ch','Securite des technologies internet (STI)'),
		 ('yvan.sayom@heig-vd.ch','Securite des technologies internet (STI)'),
		 ('gilles.kegne@heig-vd.ch','Securite des technologies internet (STI)'),
		 ('michel.archange@heig-vd.ch', 'Securite des technologies internet (STI)'),
		 ('wgallyon8@heig-vd.ch', 'Securite des systemes d exploitation (SOS)'),
		 ('lverillo9@heig-vd.ch', 'Securite des systemes d exploitation (SOS)'),
		 ('slimpenny3@heig-vd.ch', 'Securite des systemes d exploitation (SOS)'),
		 ('rpynner4@heig-vd.ch','Securite des systemes d exploitation (SOS)'),
		 ('wgallyon8@heig-vd.ch', 'Securite des reseaux (SRX)'),
		 ('lverillo9@heig-vd.ch', 'Securite des reseaux (SRX)'),
		 ('slimpenny3@heig-vd.ch', 'Securite des reseaux (SRX)'),
		 ('rpynner4@heig-vd.ch','Securite des reseaux (SRX)'),
		 ('wgallyon8@heig-vd.ch', 'Serialisation (SER)'),
		 ('lverillo9@heig-vd.ch', 'Serialisation (SER)'),
		 ('slimpenny3@heig-vd.ch', 'Serialisation (SER)'),
		 ('rpynner4@heig-vd.ch','Serialisation (SER)'),
		 ('wgallyon8@heig-vd.ch', 'Reseaux (RES)'),
		 ('lverillo9@heig-vd.ch', 'Reseaux (RES)'),
		 ('slimpenny3@heig-vd.ch', 'Reseaux (RES)'),
		 ('rpynner4@heig-vd.ch','Reseaux (RES)'),
		 ('wgallyon8@heig-vd.ch', 'Signaux analogiques et numeriques (SIG)'),
		 ('lverillo9@heig-vd.ch', 'Signaux analogiques et numeriques (SIG)'),
		 ('slimpenny3@heig-vd.ch', 'Signaux analogiques et numeriques (SIG)'),
		 ('rpynner4@heig-vd.ch','Signaux analogiques et numeriques (SIG)'),
		 ('wgallyon8@heig-vd.ch', 'Programmation orientee objet 1 (POO1)'),
		 ('lverillo9@heig-vd.ch', 'Programmation orientee objet 1 (POO1)'),
		 ('slimpenny3@heig-vd.ch', 'Programmation orientee objet 1 (POO1)'),
		 ('rpynner4@heig-vd.ch','Programmation orientee objet 1 (POO1)'),
		 ('wgallyon8@heig-vd.ch', 'Bases de donnees relationnelles (BDR)'),
		 ('lverillo9@heig-vd.ch', 'Bases de donnees relationnelles (BDR)'),
		 ('slimpenny3@heig-vd.ch', 'Bases de donnees relationnelles (BDR)'),
		 ('rpynner4@heig-vd.ch','Bases de donnees relationnelles (BDR)'),
		 ('wgallyon8@heig-vd.ch', 'Algorithmes et structures de donnees 2 (ASD2)'),
		 ('lverillo9@heig-vd.ch', 'Algorithmes et structures de donnees 2 (ASD2)'),
		 ('slimpenny3@heig-vd.ch', 'Algorithmes et structures de donnees 2 (ASD2)'),
		 ('rpynner4@heig-vd.ch','Algorithmes et structures de donnees 2 (ASD2)'),
		 ('nelson.nana@heig-vd.ch','Gestion d entreprise pour TIC (GET)'),
		 ('yvan.sayom@heig-vd.ch','Gestion d entreprise pour TIC (GET)'),
		 ('gilles.kegne@heig-vd.ch','Gestion d entreprise pour TIC (GET)'),
		 ('michel.archange@heig-vd.ch', 'Gestion d entreprise pour TIC (GET)'),
		 ('nelson.nana@heig-vd.ch','Transmission et modulation (TRM)'),
		 ('yvan.sayom@heig-vd.ch','Transmission et modulation (TRM)'),
		 ('gilles.kegne@heig-vd.ch','Transmission et modulation (TRM)'),
		 ('michel.archange@heig-vd.ch', 'Transmission et modulation (TRM)'),
		 ('nelson.nana@heig-vd.ch','Storage Area Networking (SAN)'),
		 ('yvan.sayom@heig-vd.ch','Storage Area Networking (SAN)'),
		 ('gilles.kegne@heig-vd.ch','Storage Area Networking (SAN)'),
		 ('michel.archange@heig-vd.ch', 'Storage Area Networking (SAN)'),
		 ('nelson.nana@heig-vd.ch','Teletrafic (TTR)'),
		 ('yvan.sayom@heig-vd.ch','Teletrafic (TTR)'),
		 ('gilles.kegne@heig-vd.ch','Teletrafic (TTR)'),
		 ('michel.archange@heig-vd.ch', 'Teletrafic (TTR)'),
		 ('wgallyon8@heig-vd.ch', 'Systemes d exploitation (SYE)'),
		 ('lverillo9@heig-vd.ch', 'Systemes d exploitation (SYE)'),
		 ('slimpenny3@heig-vd.ch', 'Systemes d exploitation (SYE)'),
		 ('rpynner4@heig-vd.ch','Systemes d exploitation (SYE)'),
		 ('nelson.nana@heig-vd.ch','Systemes d exploitation (SYE)'),
		 ('yvan.sayom@heig-vd.ch','Systemes d exploitation (SYE)'),
		 ('gilles.kegne@heig-vd.ch','Systemes d exploitation (SYE)'),
		 ('michel.archange@heig-vd.ch', 'Systemes d exploitation (SYE)'),
		 ('nelson.nana@heig-vd.ch','Programmation concurrente (PCO)'),
		 ('yvan.sayom@heig-vd.ch','Programmation concurrente (PCO)'),
		 ('gilles.kegne@heig-vd.ch','Programmation concurrente (PCO)'),
		 ('michel.archange@heig-vd.ch', 'Programmation concurrente (PCO)'),
		 ('wgallyon8@heig-vd.ch', 'Programmation concurrente (PCO)'),
		 ('lverillo9@heig-vd.ch', 'Programmation concurrente (PCO)'),
		 ('slimpenny3@heig-vd.ch', 'Programmation concurrente (PCO)'),
		 ('rpynner4@heig-vd.ch','Programmation concurrente (PCO)'),
		 ('nelson.nana@heig-vd.ch','Cloud Computing (CLD)'),
		 ('yvan.sayom@heig-vd.ch','Cloud Computing (CLD)'),
		 ('gilles.kegne@heig-vd.ch','Cloud Computing (CLD)'),
		 ('michel.archange@heig-vd.ch', 'Cloud Computing (CLD)'),
		 ('wgallyon8@heig-vd.ch', 'Cloud Computing (CLD)'),
		 ('lverillo9@heig-vd.ch', 'Cloud Computing (CLD)'),
		 ('slimpenny3@heig-vd.ch', 'Cloud Computing (CLD)'),
		 ('rpynner4@heig-vd.ch','Cloud Computing (CLD)'),
		 ('wgallyon8@heig-vd.ch', 'Securite des reseaux sans fil (SWI)'),
		 ('lverillo9@heig-vd.ch', 'Securite des reseaux sans fil (SWI)'),
		 ('slimpenny3@heig-vd.ch', 'Securite des reseaux sans fil (SWI)'),
		 ('rpynner4@heig-vd.ch','Securite des reseaux sans fil (SWI)'),
		 ('nelson.nana@heig-vd.ch','Projet de semestre (PRO)'),
		 ('yvan.sayom@heig-vd.ch','Projet de semestre (PRO)'),
		 ('gilles.kegne@heig-vd.ch','Projet de semestre (PRO)'),
		 ('michel.archange@heig-vd.ch', 'Projet de semestre (PRO)'),
		 ('bpierce6@heig-vd.ch','Projet de semestre (PRO)'),
		 ('cerrichelli7@heig-vd.ch', 'Projet de semestre (PRO)'),
		 ('lesly.kamdem@heig-vd.ch','Projet de semestre (PRO)'),
		 ('natacha.kegne@heig-vd.ch','Projet de semestre (PRO)'),
		 ('wgallyon8@heig-vd.ch', 'Projet de semestre (PRO)'),
		 ('lverillo9@heig-vd.ch', 'Projet de semestre (PRO)'),
		 ('slimpenny3@heig-vd.ch', 'Projet de semestre (PRO)'),
		 ('rpynner4@heig-vd.ch','Projet de semestre (PRO)'),
		 ('wgallyon8@heig-vd.ch', 'Administration IT (AIT)'),
		 ('lverillo9@heig-vd.ch', 'Administration IT (AIT)'),
		 ('slimpenny3@heig-vd.ch', 'Administration IT (AIT)'),
		 ('rpynner4@heig-vd.ch','Administration IT (AIT)'),
		 ('wgallyon8@heig-vd.ch', 'Applications multi-tiers (AMT)'),
		 ('lverillo9@heig-vd.ch', 'Applications multi-tiers (AMT)'),
		 ('slimpenny3@heig-vd.ch', 'Applications multi-tiers (AMT)'),
		 ('rpynner4@heig-vd.ch','Applications multi-tiers (AMT)'),
		 ('wgallyon8@heig-vd.ch', 'Gestion de reseaux (GRX)'),
		 ('lverillo9@heig-vd.ch', 'Gestion de reseaux (GRX)'),
		 ('slimpenny3@heig-vd.ch', 'Gestion de reseaux (GRX)'),
		 ('rpynner4@heig-vd.ch','Gestion de reseaux (GRX)');